apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zmxvp3xzj-go 
  janus-idp.io/tekton: zmxvp3xzj-go
  backstage.io/kubernetes-id: zmxvp3xzj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zmxvp3xzj-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml