apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zmxvp3xzj-go
  janus-idp.io/tekton: zmxvp3xzj-go
  backstage.io/kubernetes-id: zmxvp3xzj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zmxvp3xzj-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
